# Generated by Django 4.2.11 on 2025-03-23 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
            ],
            options={
                "verbose_name": "对话记录",
                "verbose_name_plural": "对话记录",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(max_length=20, unique=True, verbose_name="患者ID"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("age", models.PositiveIntegerField(verbose_name="年龄")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "date_registered",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="注册日期"
                    ),
                ),
                (
                    "mmse_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="MMSE分数"
                    ),
                ),
                (
                    "cdr_score",
                    models.FloatField(blank=True, null=True, verbose_name="CDR分数"),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责照护人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "患者",
                "verbose_name_plural": "患者",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("patient", "患者"), ("system", "系统")],
                        max_length=10,
                        verbose_name="发送者类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.conversation",
                        verbose_name="对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DementiaAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="评估日期"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("mild", "轻度"),
                            ("moderate", "中度"),
                            ("severe", "重度"),
                        ],
                        max_length=10,
                        verbose_name="严重程度",
                    ),
                ),
                ("confidence_score", models.FloatField(verbose_name="置信度分数")),
                (
                    "detailed_results",
                    models.JSONField(default=dict, verbose_name="详细评估结果"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="core.conversation",
                        verbose_name="相关对话",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="core.patient",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "失智症评估",
                "verbose_name_plural": "失智症评估",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="core.patient",
                verbose_name="患者",
            ),
        ),
    ]
